### ISSUE TITLE
Where is the file address ./configs/ours/ours_expt_5.yml specified in the code?

### ISSUE THREAD

**Issue by zhangmenghuan-mh** [OatmealLiu/FineR#2]
Where is the file address ./configs/ours/ours_expt_5.yml specified in the code?

**Comment by OatmealLiu** [comment]
Hi, please clone and refer to the current codebase we just released.  `./configs/ours/ours_expt_5.yml` is the file in the old repo, we used for experiments during initial exploration. It is discarded.
