### ISSUE TITLE
Does this FineR model require no training and can be evaluated directly using the data set?

### ISSUE THREAD

**Issue by zhangmenghuan-mh** [OatmealLiu/FineR#6]
Does this FineR model require no training and can be evaluated directly using the data set?

**Comment by OatmealLiu** [comment]
Yes, FineR is training-free. You can directly use/test on the given data sets or your customized datasets.

For customized datasets, you can use the Dataloder and annotation format in the current code as a reference.

**Comment by zhangmenghuan-mh** [comment]
But, if the model does not require training, then the training part (inside the red box) in the flow chart is not needed, right?
![Uploading 111.png…]()

**Comment by zhangmenghuan-mh** [comment]
But, if the model does not require training, then the training part (inside the red box) in the flow chart is not needed, right?
![111](https://github.com/OatmealLiu/FineR/assets/57607885/edf657a8-99ed-4188-8045-92d9166a47e5)

**Comment by OatmealLiu** [comment]
No. FineR operates in two macro stages. In the first stage, that is the pipeline red-boxed by you, FineR discover/reason fine-grained semantic category names (e.g., "Blackberry Lily') from the few unlabeled images. Seubsequently, the discovered names can be used to construct a multi-modal classifier along with the unlabeled images for CLIP zero-shot inference.

In the red box, there is no training conducted. Only inferences are included.

Best regards,
Mingxuan

**Comment by zhangmenghuan-mh** [comment]
thank you
