### ISSUE TITLE
Where is this file called control_discovery.py?

### ISSUE THREAD

**Issue by DraskyChen** [OatmealLiu/FineR#8]
Excuse me, when I try to run "batch_launcher_IdentifyAndHowto.sh", I cannot find "control_discovery.py" and "control_eval_grouping.py", And I only found 'discovery.py' and 'grouping.py', what's the difference between the two?

**Comment by OatmealLiu** [comment]
Hi! Thank you for poiting it out. All scripts' names "control_discovery.py" or "control_eval_grouping.py" are actually "discovering.py" and "grouping.py" in the current repo. I've corrected the script names now. Thank you for helping us improve the code.
